trigger:
  - main

pool: 'Hosted Windows 2019 with VS2019'

steps:
  - template: 'pipelines\pipeline.yml'
    parameters:
        resourceGroupName: 'dev-rg-pokebot-01'
        appServiceResourceName: 'dev-rg-pokebot-01'
        luisResourceName: 'dev-rg-pokebot-01-luis'
        resourceGroupServiceConnection: 'pokebot-connection'
        keyVaultName: 'dev-kvt-pokebot-01-hs'
        microsoftAppIdSecretName: 'microsoftAppId'
        microsoftAppPasswordSecretName: 'microsoftAppPassword'
        luisAuthoringKeySecretName: 'luisAuthoringKey'
        luisEndpointKeySecretName: 'luisEndpointKey'